# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hierro's Blog
email: agaro1121@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dametisbrown
github_username:  agaro1121

# Build settings
markdown: kramdown

# Author settings
author:
  name      : Fernando Moreira
  job       : Frontend Engineer
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  github    : http://github.com/agaro1121
  twitter   : http://twitter.com/dametisbrown
  facebook  : https://facebook.com/agaro
  linkedin  : http://linkedin.com/in/anthony-garo-b9781636